# Generated by Django 2.0 on 2023-04-13 12:04

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminemailid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('phoneno', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': True,
            },
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('artist', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('ticket_avail', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('photo1', models.CharField(blank=True, max_length=50, null=True)),
                ('photo2', models.CharField(blank=True, max_length=50, null=True)),
                ('photo3', models.CharField(blank=True, max_length=50, null=True)),
                ('likecount', models.CharField(blank=True, max_length=50, null=True)),
                ('adminemailid', models.ForeignKey(db_column='adminemailid', max_length=50, on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.Admin')),
            ],
            options={
                'db_table': 'event',
                'managed': True,
            },
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('transactionid', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=10, null=True)),
                ('eventname', models.ForeignKey(blank=True, db_column='eventname', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.Event')),
            ],
            options={
                'db_table': 'ticket',
                'managed': True,
            },
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('emailid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='User_Event_Organiser',
            fields=[
                ('eventname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('artist', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('ticket_avail', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(upload_to='pics')),
                ('likecount', models.CharField(blank=True, max_length=50, null=True)),
                ('adminemailid', models.ForeignKey(db_column='adminemailid', max_length=50, on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.Admin')),
            ],
            options={
                'db_table': 'usereventorganiser',
                'managed': True,
            },
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='userid',
            field=models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.User'),
        ),
    ]
